// AUTO-GENERATED by server/scripts/sync-shared.mjs — DO NOT EDIT.
// Edit the canonical file at repo-root shared/ instead.
/**
 * BLACKOUT — shared configuration & types.
 *
 * Imported by BOTH client and server so gameplay constants never drift. Keep it
 * dependency-free (no Three.js, no Colyseus) so it stays engine-agnostic for the
 * eventual Electron/Steam path.
 *
 * ALL gameplay magic numbers live here. Tune the game by editing CONFIG.
 */

export const CONFIG = {
  // ---- Players & roles ----
  MIN_PLAYERS: 4,
  MAX_PLAYERS: 11, // 1 Hunter + up to 10 Searchers

  // ---- Phase timings (seconds) — DEFAULTS; the host can adjust per game in the lobby ----
  HIDE_PHASE_S: 60, // Hunter setup phase (place the items); searchers roam, disoriented
  LIGHTS_ON_S: 30, // Searchers scout with full lighting; Hunter frozen
  ROUND_MAX_S: 300, // search/escape time before the round times out
  ROUND_END_S: 6, // result splash duration before the campfire
  CAMPFIRE_S: 25, // between-round regroup; auto-rematches when it expires

  // ---- Items & objectives ----
  REQUIRED_ITEMS: 3, // e.g. keys, gas tank, radio
  GOLDEN_BRICKS: 1, // extra-life / revive token
  // "Buddy-up" flashlight scarcity (host option): searchers - 1 flashlights, so
  // one searcher must always buddy up. Off (default) = one per searcher.
  flashlightsFor: (searcherCount: number) => Math.max(0, searcherCount - 1),

  // ---- Movement (units/second) ----
  SEARCHER_RUN: 6, // searchers run — fast but LOUD
  SEARCHER_WALK: 3, // searchers walk — slow but QUIET
  HUNTER_SPEED: 4, // hunter only walks — between searcher run & walk
  // Wall-climbing (Hunter only): push into a wall + hold Space/jump to scale it
  // and cling. Capped well below the 4 m wall tops so he can never cross a wall
  // — it's a perch (drop-scares, sight lines over cover), not a bypass.
  HUNTER_CLIMB_SPEED: 2.2, // vertical climb rate (units/s)
  HUNTER_CLIMB_MAX: 2.0, // max feet height while clinging

  // ---- Movement audio (audible radius, units) ----
  RUN_AUDIBLE_RADIUS: 12, // how far a running searcher can be heard
  WALK_AUDIBLE_RADIUS: 4, // how far a walking searcher can be heard

  // ---- Items ----
  PICKUP_RADIUS: 1.6, // walk this close to an item to grab it
  REVIVE_RANGE: 2, // hold the golden brick this close to a downed teammate to revive

  // ---- Combat ----
  MELEE_RANGE: 2, // forward raycast kill range for the hunter
  MELEE_MAX_DY: 1.2, // max height difference for a hit — no killing through the booth floor
  // Axe throw (optional, host-toggled): a long-range gamble — wildly inaccurate.
  AXE_RANGE: 9, // how far an axe can reach a target
  AXE_HIT_CHANCE: 0.5, // very inaccurate — 50/50 to eliminate even with a target lined up
  AXE_COOLDOWN_S: 5, // recharge between throws
  AXE_POOL: 3, // total throws per match — a scarce gamble, not a ranged spam tool

  // ---- Flashlight ----
  FLASHLIGHT_BATTERY_S: 0, // 0 = unlimited; otherwise seconds of charge
  FLICKER: true, // flashlights/lights flicker for tension

  // ---- Voice & tension cues (units) ----
  VOICE_RADIUS: 10, // proximity voice falloff distance
  HEARTBEAT_RADIUS: 8, // how close the Hunter must be to trigger heartbeat

  // ---- Dead-player troll ----
  DEAD_TROLL_COOLDOWN_S: 20,

  // ---- Hunter sabotage cooldowns (seconds) ----
  HUNTER_DOOR_LOCK_CD_S: 40,
  HUNTER_BLACKOUT_CD_S: 30,

  // ---- Traitor powers (tunable) ----
  TRAITOR_DRAIN_RANGE: 3.5, // m — close range, so "who was standing near me?" stays a real tell
  TRAITOR_DRAIN_CD_S: 25, // cooldown
  TRAITOR_DRAIN_BLIND_S: 25, // how long the drained flashlight stays dead
  TRAITOR_MARK_RANGE: 4, // m — proximity to mark a searcher
  TRAITOR_MARK_CD_S: 30, // cooldown
  TRAITOR_MARK_S: 6, // how long the Caretaker sees the mark outline
  TRAITOR_SLAM_S: 4, // Slam the Door: how long the exit is barred (3–5s tunable)
  // ---- Accusation / public hearing (tunable) ----
  ACCUSE_BEAT_S: 2.5, // dramatic beat between the claim and the verdict
  ACCUSE_MINIMAP_REVEAL_S: 45, // correct guess → Caretaker shown on the minimap
  ACCUSE_FALSE_PENALTY_S: 180, // wrong guess → accuser visible to the Caretaker (strong, but not the whole match)

  // ---- AI Caretaker (solo) ----
  AI_VISION_RANGE: 14,
  AI_VISION_FOV: 120, // degrees (full cone)
  AI_VISION_RANGE_LIT_BONUS: 8, // extra range when the target's flashlight is ON
  AI_REACTION_S: 0.45, // NOT YET IMPLEMENTED (AI spec §8): sighting-commit delay
  AI_INVESTIGATE_S: 8, // time spent poking around a last-known position
  AI_SEARCH_S: 6, // sweep time after losing a chase before giving up
  AI_GIVEUP_S: 4, // lose-of-sight grace before dropping from CHASE to SEARCH
  AI_AWARE_INVESTIGATE: 40, // awareness threshold to go investigate
  AI_AWARE_DECAY: 18, // awareness lost per second with no stimulus
  AI_MELEE_COOLDOWN_S: 1.2,
  AI_MELEE_WINDUP_S: 0.4, // swing wind-up — the player's dodge window (AI spec §8)
  AI_HEARS_HIDDEN_RADIUS: 2, // hidden-breath leak: passing this close to an occupied locker raises awareness
  AI_GUARD_PAD_THRESHOLD: 2, // once this many items are deposited (exit unlockable), the AI biases toward guarding the back EXIT + its approaches
  AI_ENDGAME_RUSH_MULT: 1.15, // doors-open speed boost (4 → 4.6): closes ground visibly, still loses a clean footrace to a running searcher (6)
  CARETAKER_RADIUS: 0.5,

  // ---- Physics / first-person feel (engine-side, not in the design table) ----
  EYE_HEIGHT: 1.7, // standing first-person camera height (units)
  CROUCH_EYE_HEIGHT: 1.0, // camera height while crouched
  CROUCH_SPEED_MULT: 0.45, // movement slowdown while crouched (vs walk)
  PLAYER_RADIUS: 0.4, // capsule radius for collision
  JUMP_SPEED: 7.8, // initial upward velocity (units/s) — clears the crates
  GRAVITY: 22, // downward acceleration (units/s^2)

  // ---- Networking ----
  // Client/server deploy separately — bump this on ANY schema or message-shape
  // change so a stale client gets "update required" instead of silent desync.
  PROTOCOL_VERSION: 5, // v5: raised stage platform + lobby-fronting restrooms (colliders/nav must match)
  SERVER_PORT: 2567,
  PATCH_RATE_HZ: 20, // state broadcast frequency
  SIM_RATE_HZ: 20, // server simulation tick (BlackoutRoom derives its interval from this)
} as const;

/** Match lifecycle phases. */
export enum Phase {
  LOBBY = "lobby",
  HIDE = "hide", // Hunter places items/flashlights
  LIGHTS_ON = "lights_on", // Searchers spawn, full light, hunter frozen
  BLACKOUT = "blackout", // power cut, hunter released
  ESCAPE = "escape", // main game, runs until win/lose
  CAMPFIRE = "campfire", // between-round regroup lobby; roles rotate
  ENDED = "ended", // win/lose resolved
}

/** Player roles. */
export enum Role {
  UNASSIGNED = "unassigned",
  HUNTER = "hunter",
  SEARCHER = "searcher",
  TRAITOR = "traitor", // a searcher secretly aiding the Hunter (Traitor mode)
}

/** Item kinds. The three REQUIRED items unlock the exit; the brick is the bonus. */
export enum ItemKind {
  KEYS = "keys",
  RADIO = "radio",
  GAS_TANK = "gas_tank",
  GOLDEN_BRICK = "golden_brick",
  FLASHLIGHT = "flashlight",
}

export const REQUIRED_ITEM_KINDS: ItemKind[] = [
  ItemKind.KEYS,
  ItemKind.RADIO,
  ItemKind.GAS_TANK,
];

/**
 * Cosmetic masks (retention unlocks). The server only VALIDATES ids against
 * this whitelist — unlock progress lives client-side (no accounts yet), so a
 * modified client could wear any mask; they're cosmetic, that's acceptable.
 * "" = no mask (default). Names/feats live client-side in profile.ts.
 */
export const MASK_IDS = [
  "comedy",
  "tragedy",
  "plague",
  "rabbit",
  "paperbag",
  "moth",
  // GLB masks (client renders from /assets/models/Glenmoor/masks/<id>.glb).
  // These are STARTER masks — unlocked from the first launch (see profile.ts).
  "clown",
  "gasmask",
  "fox",
  "masquerade",
  "anon",
] as const;
export type MaskId = (typeof MASK_IDS)[number] | "";

/**
 * Modular character outfits (ithappy pack). The server stores one JSON string
 * per player (category → piece name) and only FORMAT-validates it — the piece
 * list (manifest.json) is client-side asset data, and outfits are cosmetic, so
 * a modified client dressing itself in an unknown piece just renders nothing.
 */
export const OUTFIT_CATEGORIES = [
  "Body", "Full_Body", "Hats", "Hairs", "Glasses", "Eyebrows",
  "Mustache", "Outerwear", "Pants", "Shoe", "Gloves", "Backpack",
] as const;
export type OutfitCategory = (typeof OUTFIT_CATEGORIES)[number];

/** Validate + canonicalize an outfit JSON string. Returns "" if malformed. */
export function sanitizeOutfit(raw: string): string {
  if (!raw || raw.length > 800) return "";
  try {
    const o: unknown = JSON.parse(raw);
    if (typeof o !== "object" || o === null || Array.isArray(o)) return "";
    const out: Record<string, string> = {};
    for (const cat of OUTFIT_CATEGORIES) {
      const v = (o as Record<string, unknown>)[cat];
      if (typeof v === "string" && /^[A-Za-z][A-Za-z0-9_]{0,48}$/.test(v)) out[cat] = v;
    }
    return Object.keys(out).length ? JSON.stringify(out) : "";
  } catch {
    return "";
  }
}

/** Equippable titles = feat ids (display names live client-side in profile.ts;
 *  a test pins the two lists together). Server only whitelist-validates. */
export const TITLE_IDS = [
  "first_escape",
  "ten_escapes",
  "caught_ten",
  "medic",
  "detective",
  "blind_faith",
  "catch_me",
  "nerves",
  "shutout",
  "wolf",
  "dare_devil",
] as const;

/** Tonight's Dare — a per-round bonus objective the server announces; the
 *  client tracks completion locally (like feats). Copy lives client-side. */
export const DARE_IDS = ["brick_escape", "locker_hopper", "no_sprint", "loud_mouth"] as const;

/** How the host assigns the Hunter between rounds. */
export enum HunterMode {
  PICK = "pick", // host explicitly picks the hunter
  ROTATE = "rotate", // hunter rotates each round
}

export type Vec3 = { x: number; y: number; z: number };
