// AUTO-GENERATED by server/scripts/sync-shared.mjs — DO NOT EDIT.
// Edit the canonical file at repo-root shared/ instead.
/**
 * BLACKOUT — shared configuration & types.
 *
 * Imported by BOTH client and server so gameplay constants never drift. Keep it
 * dependency-free (no Three.js, no Colyseus) so it stays engine-agnostic for the
 * eventual Electron/Steam path.
 *
 * ALL gameplay magic numbers live here. Tune the game by editing CONFIG.
 */

export const CONFIG = {
  // ---- Mode ----
  // "solo": 1 human searcher + AI Caretaker + auto-placed loot (the test build).
  // "multiplayer": human Caretaker hides loot in HIDE phase; human searchers.
  MODE: "solo" as "solo" | "multiplayer",
  AI_SEARCHER_BOTS: 0,

  // ---- Players & roles ----
  MIN_PLAYERS: 4,
  MAX_PLAYERS: 11, // 1 Hunter + up to 10 Searchers

  // ---- Phase timings (seconds) — DEFAULTS; the host can adjust per game in the lobby ----
  HIDE_PHASE_S: 120, // Hunter-only setup phase (place the items)
  LIGHTS_ON_S: 30, // Searchers scout with full lighting; Hunter frozen
  ROUND_MAX_S: 300, // search/escape time before the round times out
  ROUND_END_S: 6, // result splash duration before the campfire
  CAMPFIRE_S: 25, // between-round regroup; auto-rematches when it expires

  // ---- Items & objectives ----
  REQUIRED_ITEMS: 3, // e.g. keys, gas tank, radio
  GOLDEN_BRICKS: 1, // extra-life / revive token
  // Flashlights handed out = searchers - 1 (one searcher must always buddy up).
  flashlightsFor: (searcherCount: number) => Math.max(0, searcherCount - 1),

  // ---- Movement (units/second) ----
  SEARCHER_RUN: 6, // searchers run — fast but LOUD
  SEARCHER_WALK: 3, // searchers walk — slow but QUIET
  HUNTER_SPEED: 4, // hunter only walks — between searcher run & walk

  // ---- Movement audio (audible radius, units) ----
  RUN_AUDIBLE_RADIUS: 12, // how far a running searcher can be heard
  WALK_AUDIBLE_RADIUS: 4, // how far a walking searcher can be heard

  // ---- Items ----
  PICKUP_RADIUS: 1.6, // walk this close to an item to grab it
  REVIVE_RANGE: 2, // hold the golden brick this close to a downed teammate to revive

  // ---- Combat ----
  MELEE_RANGE: 2, // forward raycast kill range for the hunter
  // Axe throw (optional, host-toggled): a long-range gamble — wildly inaccurate.
  AXE_RANGE: 9, // how far an axe can reach a target
  AXE_HIT_CHANCE: 0.5, // very inaccurate — 50/50 to eliminate even with a target lined up
  AXE_COOLDOWN_S: 5, // recharge between throws

  // ---- Flashlight ----
  FLASHLIGHT_BATTERY_S: 0, // 0 = unlimited; otherwise seconds of charge
  FLICKER: true, // flashlights/lights flicker for tension

  // ---- Voice & tension cues (units) ----
  VOICE_RADIUS: 10, // proximity voice falloff distance
  HEARTBEAT_RADIUS: 8, // how close the Hunter must be to trigger heartbeat

  // ---- Dead-player troll ----
  DEAD_TROLL_COOLDOWN_S: 20,

  // ---- Hunter sabotage cooldowns (seconds) ----
  HUNTER_DOOR_LOCK_CD_S: 40,
  HUNTER_BLACKOUT_CD_S: 30,
  HUNTER_SCARE_CD_S: 15,

  // ---- AI Caretaker (solo) ----
  AI_VISION_RANGE: 14,
  AI_VISION_FOV: 120, // degrees (full cone)
  AI_VISION_RANGE_LIT_BONUS: 8, // extra range when the target's flashlight is ON
  AI_REACTION_S: 0.45, // delay before committing to a fresh sighting
  AI_INVESTIGATE_S: 8, // time spent poking around a last-known position
  AI_SEARCH_S: 6, // sweep time after losing a chase before giving up
  AI_GIVEUP_S: 4, // lose-of-sight grace before dropping from CHASE to SEARCH
  AI_AWARE_INVESTIGATE: 40, // awareness threshold to go investigate
  AI_AWARE_DECAY: 18, // awareness lost per second with no stimulus
  AI_MELEE_COOLDOWN_S: 1.2,
  AI_HEARS_HIDDEN_RADIUS: 2,
  AI_GUARD_PAD_THRESHOLD: 2, // once this many items are deposited, the AI biases toward guarding the extraction pad
  CARETAKER_RADIUS: 0.5,

  // ---- Mode toggles ----
  HIDDEN_HUNTER: true, // hide the Hunter's identity until blackout
  TRAITORS: 0, // 0 = Classic; 1 = Traitor mode (recommend 6+ players)

  // ---- Physics / first-person feel (engine-side, not in the design table) ----
  EYE_HEIGHT: 1.7, // standing first-person camera height (units)
  CROUCH_EYE_HEIGHT: 1.0, // camera height while crouched
  CROUCH_SPEED_MULT: 0.45, // movement slowdown while crouched (vs walk)
  PLAYER_RADIUS: 0.4, // capsule radius for collision
  JUMP_SPEED: 7.8, // initial upward velocity (units/s) — clears the crates
  GRAVITY: 22, // downward acceleration (units/s^2)

  // ---- Networking ----
  SERVER_PORT: 2567,
  PATCH_RATE_HZ: 20, // state broadcast frequency
  SIM_RATE_HZ: 60, // server simulation tick
} as const;

/** Match lifecycle phases. */
export enum Phase {
  LOBBY = "lobby",
  HIDE = "hide", // Hunter places items/flashlights
  LIGHTS_ON = "lights_on", // Searchers spawn, full light, hunter frozen
  BLACKOUT = "blackout", // power cut, hunter released
  ESCAPE = "escape", // main game, runs until win/lose
  CAMPFIRE = "campfire", // between-round regroup lobby; roles rotate
  ENDED = "ended", // win/lose resolved
}

/** Player roles. */
export enum Role {
  UNASSIGNED = "unassigned",
  HUNTER = "hunter",
  SEARCHER = "searcher",
  TRAITOR = "traitor", // a searcher secretly aiding the Hunter (Traitor mode)
}

/** Item kinds. The three REQUIRED items unlock the exit; the brick is the bonus. */
export enum ItemKind {
  KEYS = "keys",
  RADIO = "radio",
  GAS_TANK = "gas_tank",
  GOLDEN_BRICK = "golden_brick",
  FLASHLIGHT = "flashlight",
}

export const REQUIRED_ITEM_KINDS: ItemKind[] = [
  ItemKind.KEYS,
  ItemKind.RADIO,
  ItemKind.GAS_TANK,
];

/** Game modes. */
export enum GameMode {
  CLASSIC = "classic", // Hunter vs Searchers (optional hidden Hunter)
  TRAITOR = "traitor", // adds one traitor among the searchers
}

/** How the host assigns the Hunter between rounds. */
export enum HunterMode {
  PICK = "pick", // host explicitly picks the hunter
  ROTATE = "rotate", // hunter rotates each round
}

export type Vec3 = { x: number; y: number; z: number };
