// AUTO-GENERATED by server/scripts/sync-shared.mjs — DO NOT EDIT.
// Edit the canonical file at repo-root shared/ instead.
/**
 * BLACKOUT — data-driven map: Glenmoor Playhouse (map 01).
 *
 * Engine-agnostic (no Three.js). Authored from BLACKOUT_map_glenmoor.json. Rooms
 * are rectangles; walls are GENERATED from the room boundaries with doorway gaps
 * carved from the door graph. The client builds meshes + colliders from the
 * output; the server will use the same data for nav + LOS (Track A5/A6).
 *
 * Source coords (JSON): x = east, z = south, origin top-left, z=0 = back wall,
 * front entrance at z=52. We recenter to the world origin so positions stay
 * centered (matching the centered anti-cheat bounds):
 *
 *   world.x = json.x - CX     world.z = json.z - CZ     y = up
 */

import type { Vec3 } from "./config";

export interface MapBox {
  x: number;
  y: number;
  z: number;
  w: number;
  h: number;
  d: number;
  color: number;
}

/** Axis-aligned floor zone (trigger / pad). */
export interface Zone {
  x: number;
  z: number;
  w: number;
  d: number;
}

/** A hiding spot a searcher can step into (locker, wardrobe, rack, stage wing…). */
export interface LockerDef {
  id: string;
  type: string;
  x: number;
  z: number;
  ry: number; // yaw the player faces while hidden (looking out, toward room center)
}

export interface LootAnchor {
  id: string;
  room: string;
  x: number;
  z: number;
  risk?: string;
}

export interface BlackoutMap {
  name: string;
  bounds: { w: number; d: number; h: number };
  walls: MapBox[];
  doors: DoorGap[]; // lockable doorway openings
  cover: MapBox[]; // simple solid cover blocks (props/sets)
  decals: MapBox[]; // non-colliding visual panels (e.g. sealed doors)
  lockers: LockerDef[]; // hiding spots
  pad: Zone; // extraction pad (lobby) — deposit items here (logic in A5)
  exit: Zone; // front-door escape trigger (used once doors unlock)
  barredDoor: MapBox; // solid collider blocking the front doors until unlock
  booth: { platform: MapBox; stairs: MapBox[]; walls: MapBox[]; floorY: number; access: Zone };
  searcherSpawns: Vec3[];
  hunterSpawn: Vec3;
  requiredLoot: LootAnchor[];
  goldenBrick: LootAnchor;
  flashlightAnchors: LootAnchor[];
}

// ---- Source constants ----
const CX = 36;
const CZ = 26;
const H = 4; // wall height
const T = 0.4; // wall thickness
const DOOR_W = 2.4;

const COL_WALL = 0x3a4150;
const COL_COVER = 0x4d4233;
const COL_SEALED = 0x5a2222;
const COL_BOOTH = 0x2c3340;
const COL_LADDER = 0x6a5a3a;

const wx = (x: number) => x - CX;
const wz = (z: number) => z - CZ;

// ---- Room rects in JSON coords: [x1, z1, x2, z2] ----
type Rect = { id: string; x1: number; z1: number; x2: number; z2: number };
const ROOMS_JSON: Array<[string, number, number, number, number]> = [
  ["lobby", 24, 46, 46, 52],
  ["mens", 2, 46, 12, 52],
  ["womens", 12, 46, 24, 52],
  ["gym", 46, 34, 64, 52],
  ["admin_booth", 18, 40, 24, 46], // start at x=18 so it doesn't overlap the kitchen
  ["entry_corridor", 24, 40, 40, 46],
  ["maintenance", 46, 24, 64, 34],
  ["workshop", 46, 13, 64, 24],
  ["theatre", 24, 19, 46, 40],
  ["lighting_booth", 40, 35, 46, 40], // SE corner of the theatre (out of the entry-door path)
  ["stage", 24, 13, 46, 19],
  ["back_hall", 2, 8, 64, 13],
  ["green_room", 2, 1, 26, 8],
  ["masks_closet", 28, 1, 40, 8],
  ["dressing_room", 2, 13, 20, 34],
  ["kitchen", 2, 34, 18, 44],
  ["small_hall", 18, 34, 24, 40], // extends west to x=18 to meet the kitchen (door)
  ["east_hall", 64, 8, 72, 50],
];

// Rooms in world coords, keyed by id. (lighting_booth is elevated — excluded from
// the wall/floor footprint generation; built separately as the booth platform.)
const ROOMS = new Map<string, Rect>();
for (const [id, x1, z1, x2, z2] of ROOMS_JSON) {
  ROOMS.set(id, { id, x1: wx(x1), z1: wz(z1), x2: wx(x2), z2: wz(z2) });
}

/** Room rectangles in WORLD coords — used by the client to place decor per-room. */
export type RoomRect = Rect;
export const ROOM_RECTS: RoomRect[] = Array.from(ROOMS.values());

/** Player-facing room names — MAP data, not UI copy (a second map ships its own
 *  labels; shared UI code must never hard-code these). */
export const ROOM_LABELS: Record<string, string> = {
  lobby: "Lobby",
  mens: "Men's room",
  womens: "Women's room",
  gym: "Gymnasium",
  admin_booth: "Admin booth",
  entry_corridor: "Theatre corridor",
  maintenance: "Maintenance",
  workshop: "Workshop",
  theatre: "Theatre",
  lighting_booth: "Lighting booth",
  stage: "Stage",
  back_hall: "Back hall",
  green_room: "Green room",
  masks_closet: "Costume closet",
  dressing_room: "Dressing room",
  kitchen: "Kitchen",
  small_hall: "Side hall",
  east_hall: "East hall",
};

/**
 * SOLO loot variation — each required item (and the golden brick) can spawn in any
 * of several rooms, picked fresh each solo game so the hunt isn't always identical.
 * (Multiplayer is unaffected — the Hunter places loot by hand during HIDE.)
 */
export const SOLO_LOOT_ROOMS: Record<string, string[]> = {
  keys: ["admin_booth", "green_room", "dressing_room", "kitchen", "workshop"],
  radio: ["lighting_booth", "stage", "theatre", "back_hall", "green_room"],
  gas_tank: ["maintenance", "workshop", "gym", "kitchen", "east_hall"],
  golden_brick: ["stage", "theatre", "green_room", "dressing_room", "masks_closet"],
};

/** A spawn-safe point inside a room (centre, optionally jittered toward the edges),
 *  in WORLD coords. `jitter` is 0..1 of the half-extent (kept off the walls). */
export function roomSpot(roomId: string, jitter = 0): { x: number; z: number } | null {
  const r = ROOMS.get(roomId);
  if (!r) return null;
  const x1 = Math.min(r.x1, r.x2), x2 = Math.max(r.x1, r.x2);
  const z1 = Math.min(r.z1, r.z2), z2 = Math.max(r.z1, r.z2);
  const inset = 1.0; // keep items off the walls
  const cx = (x1 + x2) / 2, cz = (z1 + z2) / 2;
  const rx = Math.max(0, (x2 - x1) / 2 - inset);
  const rz = Math.max(0, (z2 - z1) / 2 - inset);
  return { x: cx + (Math.random() * 2 - 1) * jitter * rx, z: cz + (Math.random() * 2 - 1) * jitter * rz };
}

/** The room id containing a world point (for the client's "Find: …" hint), or "". */
export function roomIdAt(x: number, z: number): string {
  for (const r of ROOM_RECTS) {
    const x1 = Math.min(r.x1, r.x2), x2 = Math.max(r.x1, r.x2);
    const z1 = Math.min(r.z1, r.z2), z2 = Math.max(r.z1, r.z2);
    if (x >= x1 && x <= x2 && z >= z1 && z <= z2) return r.id;
  }
  return "";
}

// Doors: pairs of room ids that have a passable opening between them.
//
// NOTE: several doors in the source JSON connect rooms whose rectangles don't
// actually share an edge (the coords are a rough starting layout). Those are
// re-routed here through rooms that ARE adjacent, so the building is fully
// circulable. The result has two main loops + cut-throughs:
//   • Big loop:  lobby → entry_corridor → theatre → stage → back_hall →
//                east_hall → gym → lobby
//   • West loop: theatre → stage → back_hall → dressing_room → kitchen →
//                small_hall → theatre
const DOORS: Array<[string, string]> = [
  ["lobby", "womens"],
  ["womens", "mens"], // restrooms chain off the lobby (lobby↔mens isn't adjacent)
  ["lobby", "gym"],
  ["lobby", "entry_corridor"],
  ["gym", "east_hall"], // front→east-hall via the gym (lobby↔east_hall isn't adjacent)
  ["admin_booth", "entry_corridor"],
  ["entry_corridor", "theatre"],
  ["maintenance", "workshop"],
  ["workshop", "back_hall"],
  ["east_hall", "back_hall"],
  ["back_hall", "stage"],
  ["back_hall", "stage"], // two stage-back doors
  ["back_hall", "green_room"],
  ["back_hall", "masks_closet"], // two doors into the masks closet → the exit has
  ["back_hall", "masks_closet"], // more than one approach (can't be fully sealed)
  ["back_hall", "dressing_room"],
  ["theatre", "stage"], // open (audience faces the stage)
  ["dressing_room", "kitchen"],
  ["kitchen", "small_hall"],
  ["small_hall", "theatre"],
];

// ---- Interval helpers (1D coverage along a wall line) ----
type Interval = [number, number];

function mergeIntervals(arr: Interval[]): Interval[] {
  if (arr.length === 0) return [];
  const s = arr.map((i) => [...i] as Interval).sort((a, b) => a[0] - b[0]);
  const out: Interval[] = [[...s[0]] as Interval];
  for (let i = 1; i < s.length; i++) {
    const last = out[out.length - 1];
    if (s[i][0] <= last[1] + 1e-6) last[1] = Math.max(last[1], s[i][1]);
    else out.push([...s[i]] as Interval);
  }
  return out;
}

function subtractGaps(intervals: Interval[], gaps: Interval[]): Interval[] {
  let result = intervals.map((i) => [...i] as Interval);
  for (const g of gaps) {
    const next: Interval[] = [];
    for (const [a, b] of result) {
      if (g[1] <= a || g[0] >= b) {
        next.push([a, b]);
        continue;
      }
      if (g[0] > a) next.push([a, g[0]]);
      if (g[1] < b) next.push([g[1], b]);
    }
    result = next;
  }
  return result.filter(([a, b]) => b - a > 0.05);
}

/** Shared boundary line between two world rects (for carving door gaps). */
function sharedEdge(
  a: Rect,
  b: Rect,
): { axis: "v" | "h"; line: number; span: Interval } | null {
  const eps = 0.02;
  for (const [ax, bx] of [
    [a.x2, b.x1],
    [a.x1, b.x2],
  ]) {
    if (Math.abs(ax - bx) < eps) {
      const z1 = Math.max(a.z1, b.z1);
      const z2 = Math.min(a.z2, b.z2);
      if (z2 - z1 > 0.5) return { axis: "v", line: ax, span: [z1, z2] };
    }
  }
  for (const [az, bz] of [
    [a.z2, b.z1],
    [a.z1, b.z2],
  ]) {
    if (Math.abs(az - bz) < eps) {
      const x1 = Math.max(a.x1, b.x1);
      const x2 = Math.min(a.x2, b.x2);
      if (x2 - x1 > 0.5) return { axis: "h", line: az, span: [x1, x2] };
    }
  }
  return null;
}

const key = (n: number) => n.toFixed(2);

function generateWalls(): { walls: MapBox[]; doors: DoorGap[] } {
  const doors: DoorGap[] = [];
  // Coverage: every room edge becomes a wall line; shared edges merge into one.
  const vCover = new Map<string, Interval[]>();
  const hCover = new Map<string, Interval[]>();
  const vGap = new Map<string, Interval[]>();
  const hGap = new Map<string, Interval[]>();
  const push = (m: Map<string, Interval[]>, k: string, iv: Interval) => {
    const a = m.get(k);
    if (a) a.push(iv);
    else m.set(k, [iv]);
  };

  for (const r of ROOMS.values()) {
    if (r.id === "lighting_booth") continue; // elevated, built separately
    push(vCover, key(r.x1), [r.z1, r.z2]);
    push(vCover, key(r.x2), [r.z1, r.z2]);
    push(hCover, key(r.z1), [r.x1, r.x2]);
    push(hCover, key(r.z2), [r.x1, r.x2]);
  }

  // Carve door gaps. Multiple doors between the same pair are spread along the edge.
  const pairCount = new Map<string, number>();
  const pairSeen = new Map<string, number>();
  for (const [a, b] of DOORS) {
    const pk = [a, b].sort().join("|");
    pairCount.set(pk, (pairCount.get(pk) ?? 0) + 1);
  }
  for (const [aId, bId] of DOORS) {
    const a = ROOMS.get(aId);
    const b = ROOMS.get(bId);
    if (!a || !b) continue;
    const edge = sharedEdge(a, b);
    if (!edge) continue;
    const pk = [aId, bId].sort().join("|");
    const total = pairCount.get(pk) ?? 1;
    const idx = pairSeen.get(pk) ?? 0;
    pairSeen.set(pk, idx + 1);

    const [s1, s2] = edge.span;
    const frac = (idx + 1) / (total + 1);
    let c = s1 + (s2 - s1) * frac;
    c = Math.min(s2 - DOOR_W / 2 - 0.2, Math.max(s1 + DOOR_W / 2 + 0.2, c));
    const gap: Interval = [c - DOOR_W / 2, c + DOOR_W / 2];
    push(edge.axis === "v" ? vGap : hGap, key(edge.line), gap);
    doors.push({
      id: `door${doors.length}`,
      axis: edge.axis,
      line: edge.line,
      center: c,
      width: DOOR_W,
      rooms: [aId, bId],
    });
  }

  // Real exit: the stage door at the far-back (masks-closet north exterior wall,
  // behind the theatre/backstage — the farthest point from the lobby). The front
  // lobby wall is now solid (you spawn + deposit there, then dash across to here).
  // Barred collider added separately; unlocks on objective complete OR traitor key.
  push(hGap, key(wz(1)), [wx(34) - DOOR_W / 2, wx(34) + DOOR_W / 2]);

  const walls: MapBox[] = [];
  for (const [k, ivs] of vCover) {
    const x = parseFloat(k);
    for (const [z1, z2] of subtractGaps(mergeIntervals(ivs), vGap.get(k) ?? [])) {
      walls.push({ x, y: H / 2, z: (z1 + z2) / 2, w: T, h: H, d: z2 - z1, color: COL_WALL });
    }
  }
  for (const [k, ivs] of hCover) {
    const z = parseFloat(k);
    for (const [x1, x2] of subtractGaps(mergeIntervals(ivs), hGap.get(k) ?? [])) {
      walls.push({ x: (x1 + x2) / 2, y: H / 2, z, w: x2 - x1, h: H, d: T, color: COL_WALL });
    }
  }
  return { walls, doors };
}

/** A lockable doorway opening (the Caretaker can slam it shut). */
export interface DoorGap {
  id: string;
  axis: "v" | "h"; // vertical wall line (x=line) or horizontal (z=line)
  line: number;
  center: number;
  width: number;
  rooms: [string, string]; // the two rooms this doorway connects
}

/** Collider box that fills a door opening when it's locked. */
export function doorBox(d: DoorGap): MapBox {
  return d.axis === "v"
    ? { x: d.line, y: H / 2, z: d.center, w: T, h: H, d: d.width, color: 0x6b5a2a }
    : { x: d.center, y: H / 2, z: d.line, w: d.width, h: H, d: T, color: 0x6b5a2a };
}

// ---- Cover blocks (deterministic placement within cover zones) ----
const COVER_ZONES_JSON: Array<[number, number, number, number]> = [
  [47, 35, 63, 51], // gym
  [25, 20, 45, 35], // theatre bleachers
  [3, 14, 19, 33], // dressing racks
  [47, 14, 63, 23], // workshop benches
  [3, 2, 25, 7], // green room shelves
];
function generateCover(): MapBox[] {
  const out: MapBox[] = [];
  const fracs: Array<[number, number, number]> = [
    [0.3, 0.35, 1.4],
    [0.65, 0.6, 1.2],
    [0.45, 0.8, 1.0],
  ];
  for (const [x1, z1, x2, z2] of COVER_ZONES_JSON) {
    for (const [fx, fz, s] of fracs) {
      const x = wx(x1 + (x2 - x1) * fx);
      const z = wz(z1 + (z2 - z1) * fz);
      out.push({ x, y: s / 2, z, w: s, h: s, d: s, color: COL_COVER });
    }
  }
  return out;
}

// ---- Hiding spots ----
const HIDING_JSON: Array<[string, string, number, number]> = [
  ["closet", "masks_closet", 34, 4],
  ["shelving", "green_room", 20, 5],
  ["wardrobe", "dressing_room", 6, 18],
  ["rack", "dressing_room", 15, 28],
  ["stage_wing", "stage", 26, 15],
  ["stage_wing", "stage", 44, 15],
  ["prop_gap", "gym", 50, 40],
  ["prop_gap", "gym", 60, 48],
];
function generateLockers(): LockerDef[] {
  return HIDING_JSON.map(([type, , x, z], i) => {
    const px = wx(x);
    const pz = wz(z);
    // Face toward the building center so you "look out" into the room.
    const ry = Math.atan2(-(0 - px), -(0 - pz));
    return { id: `hide${i + 1}`, type, x: px, z: pz, ry };
  });
}

// ---- Loot anchors (placed in A2) ----
const REQUIRED_LOOT: LootAnchor[] = [
  { id: "keys", room: "admin_booth", x: wx(20), z: wz(43), risk: "medium" },
  { id: "radio", room: "lighting_booth", x: wx(43), z: wz(33), risk: "high" }, // at the foot of the relocated booth stairs
  { id: "gas_tank", room: "maintenance", x: wx(55), z: wz(29), risk: "medium" },
];
const GOLDEN_BRICK: LootAnchor = { id: "golden_brick", room: "stage", x: wx(35), z: wz(16), risk: "high" };
const FLASHLIGHT_ANCHORS: LootAnchor[] = [
  { id: "fl_lobby", room: "lobby", x: wx(35), z: wz(49) },
  { id: "fl_gym", room: "gym", x: wx(55), z: wz(46) },
  { id: "fl_green", room: "green_room", x: wx(10), z: wz(4) },
  { id: "fl_dress", room: "dressing_room", x: wx(10), z: wz(22) },
  { id: "fl_back", room: "back_hall", x: wx(48), z: wz(10) },
  { id: "fl_work", room: "workshop", x: wx(55), z: wz(18) },
];

// ---- Booth (a low mezzanine in the theatre's back corner, reached by stairs) ----
// Kept low enough to stand on with ceiling clearance (H=4) and to walk up via the
// controller's step-offset. Sits in a corner so it never blocks a doorway.
const BOOTH_FLOOR_Y = 1.35; // platform top ≈ 1.5m → ~2.4m headroom under the ceiling
function buildBooth() {
  const r = ROOMS.get("lighting_booth")!;
  const cx = (r.x1 + r.x2) / 2;
  const cz = (r.z1 + r.z2) / 2;
  const platform: MapBox = {
    x: cx,
    y: BOOTH_FLOOR_Y,
    z: cz,
    w: r.x2 - r.x1,
    h: 0.3,
    d: r.z2 - r.z1,
    color: COL_BOOTH,
  };
  // Stairs on the north (room-facing) edge, ascending south up to the platform.
  const top = BOOTH_FLOOR_Y + 0.15; // walking surface
  const zNorth = Math.min(r.z1, r.z2);
  const n = 6;
  const riser = top / n; // 0.25m per step → within the step-offset, so walkable
  const tread = 0.4;
  const sw = 1.6;
  const sx = cx - 0.6;
  const stairs: MapBox[] = [];
  for (let i = 0; i < n; i++) {
    const ht = riser * (i + 1); // solid box from the floor up to this step's top
    const zc = zNorth - tread * (n - i) + tread / 2; // i=0 farthest into the room (lowest)
    stairs.push({ x: sx, y: ht / 2, z: zc, w: sw, h: ht, d: tread, color: COL_LADDER });
  }
  const access: Zone = { x: sx, z: zNorth - tread * n - 0.5, w: sw, d: 1.0 };

  // ---- Enclosure: frame each side with a sill + window opening + header (open
  //      band between them = the window) so the platform reads as its own glassed
  //      booth. A doorway gap on the north (stair) side lets you in. ----
  const walls: MapBox[] = [];
  const wt = 0.15; // wall thickness
  const wx1 = r.x1 + 0.3, wx2 = r.x2 - 0.3; // inset so the corner sides clear the building walls
  const wz1 = Math.min(r.z1, r.z2) + 0.3, wz2 = Math.max(r.z1, r.z2) - 0.3;
  const sillY = (top + (top + 0.7)) / 2, sillH = 0.7; // platform top → +0.7
  const hdrY = (top + 1.7 + (top + 2.2)) / 2, hdrH = 0.5; // header band near the top
  const seg = (orient: "h" | "v", line: number, a: number, b: number, y: number, h: number) => {
    const mid = (a + b) / 2, len = b - a;
    if (len < 0.1) return;
    walls.push(orient === "h"
      ? { x: mid, y, z: line, w: len, h, d: wt, color: COL_BOOTH }
      : { x: line, y, z: mid, w: wt, h, d: len, color: COL_BOOTH });
  };
  const side = (orient: "h" | "v", line: number, a: number, b: number) => {
    seg(orient, line, a, b, sillY, sillH); // sill (waist-high)
    seg(orient, line, a, b, hdrY, hdrH); // header (above the window)
  };
  side("v", wx1, wz1, wz2); // west (faces the house)
  side("v", wx2, wz1, wz2); // east (against the building)
  side("h", wz2, wx1, wx2); // south (against the building)
  // north: split around the stair doorway
  const doorL = sx - 0.9, doorR = sx + 0.9;
  side("h", wz1, wx1, doorL);
  side("h", wz1, doorR, wx2);
  // corner posts (full height of the frame)
  const postY = (top + (top + 2.2)) / 2, postH = 2.2;
  for (const [px, pz] of [[wx1, wz1], [wx2, wz1], [wx1, wz2], [wx2, wz2]] as const) {
    walls.push({ x: px, y: postY, z: pz, w: 0.2, h: postH, d: 0.2, color: COL_BOOTH });
  }

  return { platform, stairs, walls, floorY: BOOTH_FLOOR_Y, access };
}

// ---- Assemble ----
function makeGlenmoor(): BlackoutMap {
  const sealed: MapBox = {
    x: wx(51),
    y: H / 2,
    z: wz(1) - 0.05,
    w: 4,
    h: H * 0.85,
    d: 0.25,
    color: COL_SEALED,
  };
  // Barred collider over the relocated far-back exit door (masks-closet north
  // wall). Removed server/client when the doors unlock.
  const barredDoor: MapBox = {
    x: wx(34),
    y: H / 2,
    z: wz(1),
    w: DOOR_W,
    h: H,
    d: T,
    color: 0x6b5a2a,
  };
  const { walls, doors } = generateWalls();
  return {
    name: "Glenmoor Playhouse",
    bounds: { w: 72, d: 52, h: H },
    walls,
    doors,
    cover: generateCover(),
    decals: [sealed],
    lockers: generateLockers(),
    pad: { x: wx(35), z: wz(49), w: 4, d: 3 }, // extraction pad stays in the front lobby
    exit: { x: wx(34), z: wz(1.5), w: 3, d: 2 }, // real exit at the far-back stage door
    barredDoor,
    booth: buildBooth(),
    searcherSpawns: [
      { x: wx(28), y: 0, z: wz(49) },
      { x: wx(42), y: 0, z: wz(49) },
      { x: wx(30), y: 0, z: wz(47) },
      { x: wx(40), y: 0, z: wz(47) },
      { x: wx(35), y: 0, z: wz(50) },
    ],
    hunterSpawn: { x: wx(35), y: 0, z: wz(28) }, // mid-map (theatre) so the front→back dash is a real chase
    requiredLoot: REQUIRED_LOOT,
    goldenBrick: GOLDEN_BRICK,
    flashlightAnchors: FLASHLIGHT_ANCHORS,
  };
}

export const DEFAULT_MAP: BlackoutMap = makeGlenmoor();
