// Mirrors the canonical engine-agnostic shared/ folder into server/src/shared/.
//
// Why: the server is deployed STANDALONE to Colyseus Cloud (the upload only
// contains the server/ folder), so it can't import from ../../shared at runtime.
// We keep shared/ at the repo root as the single source of truth (the client
// imports it directly) and commit a generated mirror inside the server so the
// deployed bundle is self-contained.
//
// Runs automatically before dev/start/build. The generated files ARE committed
// so they exist in the Cloud upload; on Cloud the source folder is absent, so
// this script no-ops (the committed mirror is already in place).
import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "..", "shared"); // repo-root shared/
const dest = join(here, "..", "src", "shared"); // server-local mirror

if (!existsSync(src)) {
  // Deployed context (e.g. Colyseus Cloud): no source folder, mirror is committed.
  console.log("[sync-shared] source shared/ not found — using committed mirror.");
  process.exit(0);
}

mkdirSync(dest, { recursive: true });
const banner =
  "// AUTO-GENERATED by server/scripts/sync-shared.mjs — DO NOT EDIT.\n" +
  "// Edit the canonical file at repo-root shared/ instead.\n";

let n = 0;
for (const f of readdirSync(src)) {
  if (!f.endsWith(".ts")) continue;
  const body = readFileSync(join(src, f), "utf8");
  writeFileSync(join(dest, f), banner + body);
  n++;
}
console.log(`[sync-shared] mirrored ${n} file(s) → server/src/shared/`);
